name = "uMPS"
uuid = "7de0315c-e6c5-4c47-b21a-6226cd4ee0fb"
authors = ["yitan1 <yitam98@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
